name: diamond_gl
description: A low-level GLFW/OpenGL abstraction for building basic rendering pipelines
version: 3.0.0
repository: https://github.com/gliscowo/diamond_gl

environment:
  sdk: ^3.7.0

publish_to: https://pub.wispforest.io

dependencies:
  dart_glfw:
    hosted: https://pub.wispforest.io
    version: ^1.0.0
  dart_opengl:
    hosted: https://pub.wispforest.io
    version: ^1.0.0
  ffi: ^2.1.2
  image: ^4.5.2
  logging: ^1.2.0
  meta: ^1.12.0
  path: ^1.9.0
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
